### PR TITLE
Update swift-syntax version which compatible with Swift5.4

### PR DESCRIPTION
**Pull request by kagemiku**
## Checklist

- [x] All tests are passed.
- [ ] Added tests.
- [x] Searched existing issues to make sure not duplicated.

## Motivation and Context
To use this with Xcode12.5.1, `swift-syntax` version should be updated to compatible one.

## Description
* Update swift-syntax version which compatible with Swift5.4

### CODE REVIEW

**Comment by kagemiku** [comment]
I publish this PR with WIP to confirm GItHub Action behavior.

**Comment by kagemiku** [comment]
@ra1028 Could you approve CI execution and review this PR?

**Review by ra1028 — APPROVED** [review]
Thanks! LGTM @kagemiku

**Comment by ra1028** [comment]
CI is failing since GitHub actions doesn't support Big sur yet, but there is no other way, so I'll just merge it in.

**Pull request merged**
